apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
        - name: demo
          image: 851725405727.dkr.ecr.ap-northeast-2.amazonaws.com/gitops-demo-app:prod-0.0.0
