apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels: { app: demo }
spec:
  replicas: 2
  selector: { matchLabels: { app: demo } }
  template:
    metadata: { labels: { app: demo } }
    spec:
      containers:
        - name: demo
          image: 851725405727.dkr.ecr.ap-northeast-2.amazonaws.com/gitops-demo-app:0.0.0 # 오버레이에서 태그 패치
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 3000 }]
          readinessProbe:
            httpGet: { path: /healthz, port: 3000 }
            initialDelaySeconds: 3
