apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: 851725405727.dkr.ecr.ap-northeast-2.amazonaws.com/gitops-demo-app
    newTag: "0.0.0"
